### PR TITLE
Adding support for HTML requests

### LINKED ISSUE #26: Client changes to test PUG - server side rendering use case
@egalli Do you have client changes to test PUG implementation? Please issue a PR and refer this issue if you they can be merged with current runspec.py.

### PR DESCRIPTION
**Pull request by egalli**
Resolves #26

### CODE REVIEW

**Review by uttampawar — COMMENTED** [review]
@egalli  LGTM. Do you any have test results to add after this change? You could generate results with simple curl to show HTML result vs JSON result.

**Comment by egalli** [comment]
Attaching curl logs for /employees/name/?last_name=Evalyn
[logs.zip](https://github.com/Node-DC/Node-DC-EIS/files/1078708/logs.zip)

The sizes are close to each other
HTML: 410748
JSON: 400958

**Comment by uttampawar** [comment]
@egalli We need some complex DOM structure and it will be interesting to see the performance with PUG using runspecy client. Overall the change look good.

**Comment by egalli** [comment]
OK, I'll look into it. For now, I'll just merge the changes since they aren't related.

**Pull request merged**
