### PR TITLE
Query update towards working on latest OS and mongodb version > 2.6.x

### PR DESCRIPTION
**Pull request by octaviansoldea**
The main change consists of updating "mongoose" to "^5.3.13" when npm installing.

### CODE REVIEW

**Review by uttampawar — APPROVED** [review]
Can you elaborate on why you needed this change?

**Review by uttampawar — CHANGES_REQUESTED** [review]
Please address the question.

**Comment by octaviansoldea** [comment]
Hi Uttam

Both of the changes are required. Please see the attachment. Each repair individually does not solve the problem. Only together they enable MongoDB v3.6 or newer.

Best,
  [Octavian](
[errorsDetected.txt](https://github.com/Node-DC/Node-DC-EIS/files/2673303/errorsDetected.txt)
) Soldea

**Comment by octaviansoldea** [comment]
Hi Uttam

Both of the changes are necessary in the proposed solution. Each one still allows for a run-time error when applied independently. Together, however, they enable a smooth running when using Mongo DB v3.6.3. Please find the errors captured in the following.

Best regards,
  Octavian Soldea

Error with no changes:

---- Server ----
Starting a single instance of Node.js process with (pid: 31477)
********************************
Server running at port: 9000
********************************
Mongoose connected to the database
Constructing list of first names
Constructing list of last names
Constructing list of Addresses
{ MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:1154:66)
    at Callbacks.emit (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at Connection.messageHandler (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:295:23)
    at Socket.<anonymous> (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:289:12)
    at readableAddChunk (_stream_readable.js:270:11)
    at Socket.Readable.push (_stream_readable.js:225:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  name: 'MongoError',
  message:
   "The 'cursor' option is required, except for aggregate with the explain argument",
  ok: 0,
  errmsg:
   "The 'cursor' option is required, except for aggregate with the explain argument",
  code: 9,
  codeName: 'FailedToParse' }

---- Client ----

[12-12-2018 11:37:12] Parsing arguments.
Input options config files: config.json
Starting NODE-DC-EISv1.0 in Cluster Mode
[12-12-2018 11:37:12] Loading database with 10000 records.
In progress...
[12-12-2018 11:37:18] Loading database done.
[12-12-2018 11:37:18] Checking database consistency.
[12-12-2018 11:37:19] Database check successful.
[12-12-2018 11:37:19] Build list of employee IDs.
[12-12-2018 11:37:19] Build list of employee IDs done.
[12-12-2018 11:37:19] Build list of employee last names.
[12-12-2018 11:37:19] Build list of employee last names done.
[12-12-2018 11:37:19] Build list of address zipcodes.
[12-12-2018 11:37:19] Build list of address zipcode done.
[12-12-2018 11:37:19] Building list of Urls
[12-12-2018 11:37:19] Building list of Urls done.
[12-12-2018 11:37:19] Creating temporary log file
[12-12-2018 11:37:19] Starting meminfo collection process 
[12-12-2018 11:37:19] Starting time based run.
[12-12-2018 11:37:19] Entering RampUp time window.
[12-12-2018 11:37:19] Started processing of requests with concurrency of [200] for [100] seconds
Fatal error-No more IDs available. Aborting
[12-12-2018 11:37:19] Starting process for post processing.

------------------------------------------------------------------------------------

Error with Moongose updated only:

---- Server ----

Starting a single instance of Node.js process with (pid: 31581)
********************************
Server running at port: 9000
********************************
(node:31581) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose connected to the database
(node:31581) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Constructing list of first names
(node:31581) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
Constructing list of last names
Constructing list of Addresses
(node:31581) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
MongooseError: Mongoose 5.x disallows passing a spread of operators to `Model.aggregate()`. Instead of `Model.aggregate({ $match }, { $skip })`, do `Model.aggregate([{ $match }, { $skip }])`
    at new MongooseError (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongoose/lib/error/mongooseError.js:13:11)
    at Function.aggregate (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/mongoose/lib/model.js:3328:11)
    at getAllIds (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/controllers/employees_controller.js:378:24)
    at Layer.handle [as handle_request] (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/layer.js:95:5)
    at /home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:335:12)
    at next (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:317:13)
    at /home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:335:12)
    at next (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_mongoose/Node-DC-EIS-cluster/node_modules/express/lib/router/index.js:275:10)

---- Client ----

[12-12-2018 11:39:34] Parsing arguments.
Input options config files: config.json
Starting NODE-DC-EISv1.0 in Cluster Mode
[12-12-2018 11:39:34] Loading database with 10000 records.
In progress...
[12-12-2018 11:39:54] Loading database done.
[12-12-2018 11:39:54] Checking database consistency.
[12-12-2018 11:39:54] Database check successful.
[12-12-2018 11:39:54] Build list of employee IDs.
[12-12-2018 11:39:54] Build list of employee IDs done.
[12-12-2018 11:39:54] Build list of employee last names.
[12-12-2018 11:39:55] Build list of employee last names done.
[12-12-2018 11:39:55] Build list of address zipcodes.
[12-12-2018 11:39:55] Build list of address zipcode done.
[12-12-2018 11:39:55] Building list of Urls
[12-12-2018 11:39:55] Building list of Urls done.
[12-12-2018 11:39:55] Creating temporary log file
[12-12-2018 11:3---- Client ----9:55] Starting meminfo collection process 
[12-12-2018 11:39:55] Starting time based run.
[12-12-2018 11:39:55] Entering RampUp time window.
[12-12-2018 11:39:55] Started processing of requests with concurrency of [200] for [100] seconds
Fatal error-No more IDs available. Aborting
[12-12-2018 11:39:55] Starting process for post processing.

------------------------------------------------------------------------------------

Error with code change updated only:

---- Server ----

Starting a single instance of Node.js process with (pid: 32132)
********************************
Server running at port: 9000
********************************
Mongoose connected to the database
Constructing list of first names
Constructing list of last names
Constructing list of Addresses
{ MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_code_change/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_code_change/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:1154:66)
    at Callbacks.emit (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_code_change/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at Connection.messageHandler (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_code_change/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/topologies/server.js:295:23)
    at Socket.<anonymous> (/home/octavian/Octavian/2018/12December/12/Node-DC-EIS_v_1_2_0_pure_code_change/Node-DC-EIS-cluster/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:289:12)
    at readableAddChunk (_stream_readable.js:270:11)
    at Socket.Readable.push (_stream_readable.js:225:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  name: 'MongoError',
  message:
   "The 'cursor' option is required, except for aggregate with the explain argument",
  ok: 0,
  errmsg:
   "The 'cursor' option is required, except for aggregate with the explain argument",
  code: 9,
  codeName: 'FailedToParse' }


---- Client ----

[12-12-2018 11:54:23] Parsing arguments.
Input options config files: config.json
Starting NODE-DC-EISv1.0 in Cluster Mode
[12-12-2018 11:54:23] Loading database with 10000 records.
In progress...
[12-12-2018 11:54:29] Loading database done.
[12-12-2018 11:54:29] Checking database consistency.
[12-12-2018 11:54:29] Database check successful.
[12-12-2018 11:54:29] Build list of employee IDs.
[12-12-2018 11:54:29] Build list of employee IDs done.
[12-12-2018 11:54:29] Build list of employee last names.
[12-12-2018 11:54:29] Build list of employee last names done.
[12-12-2018 11:54:29] Build list of address zipcodes.
[12-12-2018 11:54:29] Build list of address zipcode done.
[12-12-2018 11:54:29] Building list of Urls
[12-12-2018 11:54:29] Building list of Urls done.
[12-12-2018 11:54:29] Creating temporary log file
[12-12-2018 11:54:29] Starting meminfo collection process 
[12-12-2018 11:54:29] Starting time based run.
[12-12-2018 11:54:29] Entering RampUp time window.
[12-12-2018 11:54:29] Started processing of requests with concurrency of [200] for [100] seconds
Fatal error-No more IDs available. Aborting
[12-12-2018 11:54:29] Starting process for post processing.

**Comment by octaviansoldea** [comment]
Hi Uttam

Updated all the indications. Could you please check?

Best regards,
  Octavian Soldea

**Review by uttampawar — APPROVED** [review]
LGTM.

**Comment by uttampawar** [comment]
Thanks for the submission.

**Pull request merged**
