### PR TITLE
Fix: #83 - MongoDB initialization in cluster mode

### LINKED ISSUE #83: MongoDB initialization in cluster mode
Hello

When trying cluster more, I observed some random problems. The server does not begin to run due to the fact that MongoDB is not initialized well. Please see start-server.sh:

if [ -f server-input.txt ]; then
        port=`grep db_port server-input.txt | cut -d':' -f2`
        if [ "x$port" == "x" ]; then
                echo "Mongodb port is not set. Instance will not be started"
                exit 1
        fi
        mongod --dbpath ./mongodb.template --port $port > /dev/null &
else
        echo "Expected - mongodb to be running at the port specified in server config"
fi
echo "Installing npm modules"
npm install
echo "Starting server"
node server-cluster.js &
sleep 5
exit 0

Thank you in advance,
  @octaviansoldea

### PR DESCRIPTION
**Pull request by octaviansoldea**
The cluster mode does not start always due to the fact that
the initialization of mongodb takes some time and the server
is run before this. This phenomenon happens randonly.

Fix: #83

### CODE REVIEW

**Review by uttampawar — CHANGES_REQUESTED** [review]
Can you put mongodb.$port.log into mongodb.template directory instead of /tmp. That way everything will be in one place and easy to verify mongodb logs in case of database issue.

**Comment by octaviansoldea** [comment]
mongodb.$port.log is written into mongodb.template now.

**Review by uttampawar — CHANGES_REQUESTED** [review]
Please time-bound test to come out of the infinite loop.

**Comment by octaviansoldea** [comment]
Hello

All the requested changes were implemented. Could you please provide feedback?

Thank you in advance,
       @octaviansoldea

**Review by uttampawar — APPROVED** [review]
LGTM

**Pull request merged**
