### PR TITLE
Configurable files for cluster mode.

### PR DESCRIPTION
**Pull request by octaviansoldea**
This patch is in response to issue #88.

### CODE REVIEW

**Review by uttampawar — CHANGES_REQUESTED** [review]
1) It's too many redirection by putting few variables in another ".sh" file. What are we exporting from ".sh" file?
2) What happens with all those variables when ".sh" is not found? For e.g. "no_graph". All variables should start with default values before you source any external environment.
3) Strongly advising against doing blind copy as "cp start-server*.sh". Avoid "*" for any shell operation.

**Comment by octaviansoldea** [comment]
Hi @uttampawar 

Thank you very much for the good feedback. Agreed with point 3 and changed the code. Please see the new submission.

Regarding 1 and 2 I would be happy to receive a bit more feedback. The variable no_graph has the default value if not set from environment.

Thank you in advance,
   @octaviansoldea

**Comment by octaviansoldea** [comment]
Hi @uttampawar 

Thank you for the good suggestions and the follow up. I implemented all the changes required.
Could you please check?

Thank you in advance,
  @octaviansoldea

**Comment by uttampawar** [comment]
> Hi @uttampawar
> 
> Thank you for the good suggestions and the follow up. I implemented all the changes required.
> Could you please check?
> 
> Thank you in advance,
> @octaviansoldea

1) Please update the usage statement.
It should be something like,
Usage: run_multiple_instance.sh <runtype> <node path>
runtype: 0 - bare metal, 1 - container
path: Path to the node executable 

2) no_graph=true make this default outside the "if"statement. In fact I don't think you need "if" check at all. 

3) In start-server.sh script, please add check to verify the existence of 'node' executable, after setting the path.

**Review by uttampawar — CHANGES_REQUESTED** [review]
See my comments.

**Review by uttampawar — APPROVED** [review]
LGTM

**Comment by uttampawar** [comment]
Patch is merged.

**Pull request merged**
